Update install_dependencies

diff --git a/scripts/install_dependencies b/scripts/install_dependencies
--- a/scripts/install_dependencies
+++ b/scripts/install_dependencies
@@ -5,41 +5,33 @@ set -e
 CATALINA_HOME=/usr/share/tomcat7-codedeploy
 TOMCAT_VERSION=7.0.77
 
-# Tar file name
-TOMCAT7_CORE_TAR_FILENAME="apache-tomcat-$TOMCAT_VERSION.tar.gz"
-# Download URL for Tomcat7 core
-TOMCAT7_CORE_DOWNLOAD_URL="https://archive.apache.org/dist/tomcat/tomcat-7/v$TOMCAT_VERSION/bin/$TOMCAT7_CORE_TAR_FILENAME"
-# The top-level directory after unpacking the tar file
-TOMCAT7_CORE_UNPACKED_DIRNAME="apache-tomcat-$TOMCAT_VERSION"
+# Check if required tools are available
+command -v wget >/dev/null 2>&1 || { echo >&2 "wget is required but not installed. Aborting."; exit 1; }
+command -v tar >/dev/null 2>&1 || { echo >&2 "tar is required but not installed. Aborting."; exit 1; }
 
-
-# Check whether there exists a valid instance
-# of Tomcat7 installed at the specified directory
-[[ -d $CATALINA_HOME ]] && { service tomcat7 status; } && {
-    echo "Tomcat7 is already installed at $CATALINA_HOME. Skip reinstalling it."
+# Check whether Tomcat7 is already installed and running
+if systemctl is-active --quiet tomcat7; then
+    echo "Tomcat7 is already installed and running. Skip reinstalling it."
     exit 0
-}
+fi
 
 # Clear install directory
-if [ -d $CATALINA_HOME ]; then
-    rm -rf $CATALINA_HOME
-fi
-mkdir -p $CATALINA_HOME
+rm -rf "$CATALINA_HOME"
+mkdir -p "$CATALINA_HOME"
+
+# Install libxslt package
+sudo yum install -y libxslt || { echo "Failed to install libxslt package"; exit 1; }
 
 # Download the latest Tomcat7 version
 cd /tmp
-{ which wget; } || { yum install -y wget; }  # Added -y option here
-wget $TOMCAT7_CORE_DOWNLOAD_URL
-if [[ -d /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME ]]; then
-    rm -rf /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME
-fi
-tar xzf $TOMCAT7_CORE_TAR_FILENAME
+wget -q "$TOMCAT7_CORE_DOWNLOAD_URL"
+tar xzf "$TOMCAT7_CORE_TAR_FILENAME"
 
-# Copy over to the CATALINA_HOME
-cp -r /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME/* $CATALINA_HOME
+# Copy Tomcat files to CATALINA_HOME
+cp -r "/tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME"/* "$CATALINA_HOME"
 
 # Install Java if not yet installed
-{ which java; } || { yum install -y java; }  # Added -y option here
+command -v java >/dev/null 2>&1 || { sudo yum install -y java; }
 
 # Create the service init.d script
 cat > /etc/init.d/tomcat7 <<'EOF'
@@ -67,3 +59,6 @@ EOF
 
 # Change permission mode for the service script
 chmod 755 /etc/init.d/tomcat7
+
+# Inform user that installation is complete
+echo "Tomcat7 installation completed successfully."
